sudo: required

services:
  - docker

language: go

matrix:
  include:
    - go: "1.13"

go_import_path: github.com/GoogleCloudPlatform/k8s-stackdriver

install:
  - hack/install-verify-tools.sh
  - export PATH=$GOPATH/bin:$PATH
  - hack/for-go-proj.sh install

script:
  - hack/verify-all.sh -v
  - hack/for-go-proj.sh test
